title: 忞月の博客
subtitle: 要快乐哦！
description: 今天你做了什么？
keywords: null
author: 忞月
language: zh-CN
timezone: Asia/Shanghai #中国的时区，不要乱改城市
url: 'http://minyuehe.github.io'
root: /
permalink: ':year/:month/:day/:title/'
permalink_defaults: null
pretty_urls:
  trailing_index: true
  trailing_html: true
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: ':lang'
skip_render: null
new_post_name: ':title.md'
default_layout: post
titlecase: false
external_link:
  enable: true
  field: site
  exclude: ''
filename_case: 0
render_drafts: false
post_asset_folder: true
relative_link: false
future: true
highlight:
  enable: false
  line_number: true
  auto_detect: false
  tab_replace: ''
  wrap: true
  hljs: false
prismjs:
  enable: true
  preprocess: true
  line_number: true
  tab_replace: ''
index_generator:
  path: ''
  per_page: 12
  order_by: '-date'
default_category: uncategorized
category_map: null
tag_map: null
meta_generator: true
date_format: YYYY-MM-DD
time_format: 'HH:mm:ss'
updated_option: mtime
per_page: 12
pagination_dir: page
include: null
exclude: null
ignore: null
theme: next
deploy:
  type: git
  repo: 'git@github.com:minyuehe/minyuehe.github.io.git'
  branch: master
  repository: 'git@github.com:minyuehe/minyuehe.github.io.git'
githubEmojis:
  enable: true
  className: github-emoji
  inject: true
  styles: null
  customEmojis: null

search:
path: search.xml
field: post
format: html
limit: 10000
permalink_pinyin:
  enable: true
  separator: '-'
lazyload:
  enable: true
  onlypost: false
  loadingImg: null

excerpt:
  depth: 5
  excerpt_excludes: []
  more_excludes: []
  hideWholePostExcerpts: true

# hexo-tag-cloud
tag_cloud:
  textFont: Trebuchet MS, Helvetica
  textColor: '#ffb6c1'
  textHeight: 21
  outlineColor: '#470024'
  maxSpeed: 0.2
  pauseOnSelected: true # true 意味着当选中对应 tag 时,停止转动
